// The twenty machine-checkable constraints of the 2026-08-25 comparison (exp-p1.mjs), extracted verbatim as a module.
const stripFence = t => t.replace(/```json|```/g, '').trim();
const words = t => t.split(/\s+/).filter(Boolean);
const sentences = t => t.split(/(?<=[.!?])\s+/).map(s => s.trim()).filter(Boolean);
export const C20 = [
  { id: 'words-20', prompt: 'Write one sentence of exactly 20 words. Output only the sentence.', check: t => { const n = words(t).length; return { pass: n === 20, reason: `has ${n} words, need exactly 20` }; } },
  { id: 'words-33', prompt: 'Write exactly 33 words. Output only the text.', check: t => { const n = words(t).length; return { pass: n === 33, reason: `has ${n} words, need exactly 33` }; } },
  { id: 'no-e-2sent', prompt: 'Write two sentences that contain no letter e. Output only the sentences.', check: t => ({ pass: !/[eE]/.test(t) && sentences(t).length >= 2, reason: /[eE]/.test(t) ? 'contains the letter e' : 'fewer than two sentences' }) },
  { id: 'no-a-1sent', prompt: 'Write one sentence that contains no letter a. Output only the sentence.', check: t => ({ pass: !/[aA]/.test(t) && sentences(t).length >= 1, reason: /[aA]/.test(t) ? 'contains the letter a' : 'not a sentence' }) },
  { id: 'lower-nocomma-25to30', prompt: 'Write 25 to 30 words, all lowercase, with no commas. Output only the text.', check: t => { const n = words(t).length; const ok = t === t.toLowerCase() && !t.includes(',') && n >= 25 && n <= 30; return { pass: ok, reason: t !== t.toLowerCase() ? 'has uppercase' : t.includes(',') ? 'has a comma' : `has ${n} words, need 25 to 30` }; } },
  { id: 'json-nac', prompt: 'Output only valid JSON with exactly the keys name, age, city. No prose.', check: t => { try { const o = JSON.parse(stripFence(t)); return { pass: Object.keys(o).sort().join(',') === 'age,city,name', reason: 'keys are ' + Object.keys(o).join(',') }; } catch { return { pass: false, reason: 'not valid JSON' }; } } },
  { id: 'json-tyr-num', prompt: 'Output only valid JSON with exactly the keys title, year, rating, where rating is a number. No prose.', check: t => { try { const o = JSON.parse(stripFence(t)); return { pass: Object.keys(o).sort().join(',') === 'rating,title,year' && typeof o.rating === 'number', reason: 'keys/type wrong' }; } catch { return { pass: false, reason: 'not valid JSON' }; } } },
  { id: 'bullets-4', prompt: 'Output exactly 4 bullet points, each line starting with "- ". No other text.', check: t => { const n = t.split('\n').filter(l => l.trim().startsWith('- ')).length; return { pass: n === 4, reason: `has ${n} bullets, need 4` }; } },
  { id: 'bullets-6', prompt: 'Output exactly 6 bullet points, each line starting with "- ". No other text.', check: t => { const n = t.split('\n').filter(l => l.trim().startsWith('- ')).length; return { pass: n === 6, reason: `has ${n} bullets, need 6` }; } },
  { id: 'each-sent-S', prompt: 'Write 3 sentences where every sentence starts with the letter S. Output only the sentences.', check: t => { const s = sentences(t); const ok = s.length >= 3 && s.every(x => /^s/i.test(x)); return { pass: ok, reason: 'a sentence does not start with S or fewer than 3' }; } },
  { id: 'data-x3', prompt: 'Write a short paragraph in which the word "data" appears exactly 3 times. Output only the paragraph.', check: t => { const n = (t.toLowerCase().match(/\bdata\b/g) || []).length; return { pass: n === 3, reason: `"data" appears ${n} times, need 3` }; } },
  { id: 'secure-x2-le40', prompt: 'Write at most 40 words in which the word "secure" appears exactly twice. Output only the text.', check: t => { const n = (t.toLowerCase().match(/\bsecure\b/g) || []).length; const w = words(t).length; return { pass: n === 2 && w <= 40, reason: `"secure" x${n} (need 2), ${w} words (max 40)` }; } },
  { id: 'lines-3', prompt: 'Output exactly 3 lines. Output only those 3 lines.', check: t => { const n = t.split('\n').filter(l => l.trim()).length; return { pass: n === 3, reason: `has ${n} nonempty lines, need 3` }; } },
  { id: 'sent-5', prompt: 'Write exactly 5 sentences. Output only the sentences.', check: t => { const n = sentences(t).length; return { pass: n === 5, reason: `has ${n} sentences, need 5` }; } },
  { id: 'short-words-15', prompt: 'Write at least 15 words where no word is longer than 6 letters. Output only the text.', check: t => { const w = words(t).map(x => x.replace(/[^A-Za-z]/g, '')); const bad = w.find(x => x.length > 6); return { pass: w.length >= 15 && !bad, reason: bad ? `word "${bad}" > 6 letters` : `only ${w.length} words` }; } },
  { id: 'two-digits', prompt: 'Write a sentence containing exactly two digit characters. Output only the sentence.', check: t => { const n = (t.match(/[0-9]/g) || []).length; return { pass: n === 2, reason: `has ${n} digits, need exactly 2` }; } },
  { id: 'ends-phrase', prompt: 'Write two sentences that end with the exact phrase: end of report. Output only the text.', check: t => ({ pass: /end of report\.?$/i.test(t.trim()), reason: 'does not end with "end of report"' }) },
  { id: 'words-50', prompt: 'Write exactly 50 words. Output only the text.', check: t => { const n = words(t).length; return { pass: n === 50, reason: `has ${n} words, need exactly 50` }; } },
  { id: 'json-arr-3', prompt: 'Output only a valid JSON array of exactly 3 strings. No prose.', check: t => { try { const a = JSON.parse(stripFence(t)); return { pass: Array.isArray(a) && a.length === 3 && a.every(x => typeof x === 'string'), reason: 'not a 3-string array' }; } catch { return { pass: false, reason: 'not valid JSON' }; } } },
  { id: 'titlecase-12', prompt: 'Write exactly 12 words in Title Case (every word capitalized). Output only the text.', check: t => { const w = words(t); const ok = w.length === 12 && w.every(x => /^[^a-z]/.test(x)); return { pass: ok, reason: w.length !== 12 ? `has ${w.length} words` : 'a word is not capitalized' }; } },
];
